project:
  type: website
  output-dir: docs

website:
  title: "GSoC'25 | NumFOCUS | NetworkX"
  navbar:
    right:
      - about.qmd
      - icon: github
        text: Github
        href: https://github.com/akshitasure12
  body-footer: |
    © 2025 Akshita Sure

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



